Connection protocol extention
KMM2019-CrazyTaxi/remote-module pull request #10
Opened 2019-11-27 14:30 UTC by Henkecool

# Connection protocol extention

* Add PID Control Parameters sending and requesting.
* Add PID Control datastructure.
* Update RemoteData, RequestBuilder and Server to allow for more control of what packet is sent when a RemoteData requests and update to its value.
* Add Double/byte[] data conversion.

## Relevant issues
#3 WIP.

## Testing
None

2019-12-01 15:06 UTC, Gravenstein requested changes
Ser mestadels rimligt ut. Jag har lämnat några kommentarer du gärna får titta på.

2019-12-01 15:06 UTC, Gravenstein commented on src/enums/PIDControlerType.java
> +        if ((b & 0xff) > PIDControlerType.values().length)
Vad är syftet med bitwise and här? En byte är alltid åtta bitar, så b & 0xff borde alltid returnera b.

2019-12-01 15:06 UTC, Gravenstein commented on src/remote/Car.java
> +    public RemoteData<Double> distanceToStop;
Vi kommer att mäta avstånd till kantlinjerna på två olika avstånd. Just nu har vi bara ett avstånd, men det ska helst vara lätt att lägga till det andra avståndet i protokollet/gui när det är tillgängligt.

2019-12-01 15:06 UTC, Gravenstein commented on src/remote/Car.java
> +    public RemoteData<Double> distanceToMiddle;
Denna tror jag inte görs tillgänglig på detta sätt. Det beräknas internt i regleringen, men sparas inte i centralmodulens dataregister.

2019-12-02 10:51 UTC, Henkecool commented on src/enums/PIDControlerType.java
> +        if ((b & 0xff) > PIDControlerType.values().length)
Bytewise and är endast definierad på Integer i Java vilket resulterar i en implicit konvertering till Int. Att sedan maska av 0xFF ger byte-värdet utan tecken (eftersom bytes i Java annars är signed)

2019-12-02 11:02 UTC, Henkecool commented on src/remote/Car.java
> +    public RemoteData<Double> distanceToMiddle;
Denna läsning skall implementeras med en kommande request/respons i kommunikationsprotokollet

2019-12-03 08:51 UTC, Henkecool commented on src/remote/Car.java
> +    public RemoteData<Double> distanceToStop;
Detta är ännu inte del av kommunikationsprotokollet och kommer därav implementeras senare.

2019-12-03 09:52 UTC, Gravenstein approved these changes
Ser bra ut!

2019-12-03 21:29 UTC, merged