Connection protocol
KMM2019-CrazyTaxi/remote-module pull request #4
Opened 2019-11-21 16:15 UTC by Henkecool

# Connection protocol

The base connection protocol structure and the protocol estabished so far is is implemented.

* Add RemoteData abstraction
* Add WIP Car model
* Add WIP Server class for handeling packets
* Add listeners for Acknowledgement, Errors, Exceptions and Updates
* Add runnable fixed time puller
* Add CommunicationPacket class for representing data packets
* Add PacketList class for containting list of CommunicationPackets
* Add RequestBuilder class for convenient building of PacketLists to be sent by server
* Add enumerations for a bunch of things
* Add RequestIDBroker class for generating and keeping track of used packet ID:s
* Add two test mockups

## Relevant issues
Fixes #2. #3 now WIP.

## Testing
Basic testing with mockup server was conducted.

## Assignees
Tag and assign the collaborators responsible for solving the pull request and the collaborator that is responsible for giving a code review.

2019-11-22 15:56 UTC, angloth requested changes
Ok boomer

2019-11-22 15:56 UTC, angloth commented on src/enums/ControlMode.java
> +        return ControlMode.values()[b];
Might need check of the input byte to avoid index error

2019-11-22 15:56 UTC, angloth commented on src/enums/PacketCommand.java
> +        return PacketCommand.values()[ord];
Might need an index check on 'ord' aswell?

2019-11-22 15:56 UTC, angloth commented on src/remote/Car.java
> +    public Car() {
Constructor should be private for a true singleton.

2019-11-22 15:56 UTC, angloth commented on src/remote/RequestBuilder.java
> +//    }
Would prefer to remove outcommented code.

2019-11-22 15:56 UTC, angloth commented on src/remote/RequestBuilder.java
> +//    }
Outcommented code

2019-11-22 15:56 UTC, angloth commented on src/remote/RequestIDBroker.java
> +    }
Lol

2019-11-22 15:56 UTC, angloth commented on src/remote/Server.java
> +    public Server() {
Public constructor for Singleton

2019-11-22 16:59 UTC, Henkecool commented on src/remote/RequestBuilder.java
> +//    }
This is WIP. Will be resolved when communication protocol is established

2019-11-22 17:00 UTC, Henkecool commented on src/remote/RequestBuilder.java
> +//    }
This is WIP. Will be resolved when communication protocol is fully established

2019-11-22 17:00 UTC, Henkecool commented on src/remote/RequestIDBroker.java
> +    }
xD

2019-11-22 17:03 UTC, Henkecool reviewed
New changes added to resolve pull request comments.

2019-11-25 12:15 UTC, Bence657 approved these changes
Ok






























Boomer

2019-11-25 14:48 UTC, angloth approved these changes
OK

2019-11-25 15:18 UTC, merged